### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-carousel#12]
# User story

The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v2.0-rc` branch.

## Outline subtasks or tasks

- [ ] default for arrow display boolean #11 
- [ ] scroll 100% #10 
- [ ] upgrade #6 

### Prior to next major release 

It is **important that we communicate prior to the next major release** that we will be changing the npm namespace. See https://github.com/AlaskaAirlines/auro-radio/commit/2e894a0af517b633a4b24cbc2b3156cd96487d1d for the update to be used. 

## Development process

This is a placeholder issue for all the issues to be in a single release. As each issue is put into play, please update the issue as IN PROGRESS and move it into the WIP column. Please leave this issue in TO DO until all linked issues are completed.

## Definition of “Done” (exit criteria)

This issue will be considered complete and all features released once all issues listed are considered complete.

**Comment by braven112** [comment]
Closing this rc in favor of issues and milestones
