### ISSUE TITLE
auro-carousel: blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-carousel#14]
# Blueprint
We need a blueprint for auro-carousel that matches the features we have currently on our doc site.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by leeejune** [comment]
Component published on Figma. Blueprint has not been completed.

**Comment by blackfalcon** [comment]
When an issue is complete, please CLOSE the issue and do not manually move it to DONE. This is automated with the closing of an issue.

**Comment by leeejune** [comment]
@blackfalcon This is technically not complete because the blueprint is still not done. Only a part of it has been completed (publishing the component on Figma) because the blueprints are not our current priority.
