### ISSUE TITLE
Dependency on node-sass breaks modern builds 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-carousel#18]
## Describe the bug

See the following PR

- https://github.com/AlaskaAirlines/auro-carousel/pull/17

The scope of this issue is to update this project to use dart-sass versus node-sass via the updated wc-sass-render package. This will allow for modern builds with node 16.

**Comment by jordanchang** [comment]
Is this still an issue? It appears we can build with version 2.0.0, but results in a CSS runtime error.

![image](https://github.com/AlaskaAirlines/auro-carousel/assets/3304352/8d50676c-9c9c-4d25-8d6b-730fda2fef61)

**Comment by blackfalcon** [comment]
I consulted @jordanchang via screen share and observed the error. The team was advised to revert back to v1.4.0 in order to have a stable app until the underlying issue can be resolved. 

To address this, I will do a complete review of the 2.0.0 release diff and see if I can discover what the corrective action is to take. WIth a working resolution, I intend to review the update with @jordanchang project before calling this fixed.

**Comment by braven112** [comment]
@blackfalcon Does this issue have to be addressed before we can complete this one? https://github.com/AlaskaAirlines/auro-carousel/issues/32

**Comment by blackfalcon** [comment]
> @blackfalcon Does this issue have to be addressed before we can complete this one? #32

Yes

**Comment by blackfalcon** [comment]
This issue should be resolved. Following up with @danhiel to verify this has been addressed.
