### ISSUE TITLE
Gradient not working correctly.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-carousel#51]
### Please describe the bug

Go to auro docsite
go to carousel
see gradient is initially not their
After interacting you can see a gradient but it is turned 90 degrees

### Reproducing the error

None

### Expected behavior

Gradient should always be shown and gradient should fade into background to the right or left instead of up and down.

**Comment by Patrick-Daly-AA** [comment]
see figma for expected look: https://www.figma.com/design/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?m=auto&node-id=3693-13840&t=AOFbOhrYnvi6m0QH-1
