### ISSUE TITLE
Upgrade to new generator build

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-carousel#6]
## Is your feature request related to a problem? Please describe.

Update repo to a new generator build. 
https://auro.alaskaair.com/getting-started/developers/generator/upgrade

This will also include publishing to the new `@aurodesignsystem` namespace

**Comment by blackfalcon** [comment]
On hold until WC-Generator 3.0 is released

**Comment by jordanjones243** [comment]
Repo has been updated using new version of generator, hence this issue is closed.
